export const vsDarkPlus = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'string', foreground: 'CE9178' },
    { token: 'string.key.json', foreground: '9CDCFE' },
    { token: 'number', foreground: 'B5CEA8' },
    { token: 'number.json', foreground: 'B5CEA8' },
    { token: 'keyword', foreground: '569CD6' },
    { token: 'keyword.json', foreground: '569CD6' },
    { token: 'delimiter', foreground: 'D4D4D4' },
    { token: 'delimiter.bracket', foreground: 'D4D4D4' },
    { token: 'delimiter.array', foreground: 'D4D4D4' },
    { token: 'delimiter.comma', foreground: 'D4D4D4' },
    { token: 'delimiter.colon', foreground: 'D4D4D4' },
  ],
  colors: {
    'editor.background': '#1F1F1F',
    'editor.foreground': '#D4D4D4',
    'editorLineNumber.foreground': '#858585',
    'editorLineNumber.activeForeground': '#C6C6C6',
    'editor.selectionBackground': '#264F78',
    'editor.selectionHighlightBackground': '#2D2D30',
    'editor.wordHighlightBackground': '#575757',
    'editor.wordHighlightStrongBackground': '#004972',
    'editorCursor.foreground': '#AEAFAD',
    'editorWhitespace.foreground': '#3B3B3B',
    'editorIndentGuide.background': '#404040',
    'editorIndentGuide.activeBackground': '#707070',
    'editor.lineHighlightBackground': '#2D2D30',
    'editor.lineHighlightBorder': '#282828',
  },
};
