name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests with coverage
        run: npm test

      - name: Build
        run: |
          npm run build
          ls -la
          ls -la .next || echo "No .next directory found"
        env:
          CI: true
          NODE_ENV: production

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage/
            junit.xml
          retention-days: 30

      - name: Upload build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next/
            public/
          if-no-files-found: error
          retention-days: 7
